# Generated by Django 3.2.4 on 2021-06-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='accessing_account',
        ),
    ]
