# Generated by Django 3.2.4 on 2021-06-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='members',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='members',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatting.contacts'),
        ),
    ]
