# Generated by Django 3.2.4 on 2021-06-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_auto_20210608_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='individual_chart',
            new_name='individual_chat',
        ),
    ]
