# Generated by Django 3.2.4 on 2021-06-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_remove_settings_accessing_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='chat',
            new_name='group_chat',
        ),
        migrations.RenameField(
            model_name='groupchat',
            old_name='name',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='call',
            name='mode_of_call',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualchat',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_privacy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='type_of_call',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_chat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatting.groupchat')),
                ('individual_chart', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatting.individualchat')),
            ],
        ),
    ]
